---
- name: Creating the users .
  user:
    name: "{{ sname }}"
    password: "{{ 'mohan' | password_hash('sha512')  }}"
    comment:  "{{ sfull }}"
    shell:  /bin/bash
    group:  tower
    groups: tower
    home: /home/{{  sname }}
